inteiro = int(20)
print(inteiro)
print(type(inteiro))
decimal = float(1.5)
print(decimal)
print(type(decimal))
booleano = bool(True)
print(booleano)
print(type(booleano))
string = str('string')
print(string)
print(type(string))
n1 = input('Digite uma string: ')
print(n1)
print(type(n1))
n2 = int(input('Digite um número inteiro: '))
print(n2)
print(type(n2))
n3 = float(input('Digite um número decimal: '))
print(n3)
print(type(n3))
